GET  http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "aaa",
    "number" : "12341213"
}

###
DELETE   http://localhost:3001/api/persons/3